name: Version Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -Pversion=${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/Core-${{ github.ref_name }}.jar
